Repository edualgo/eduAlgo, pull requests merged in 2020-10, with the labels that each got.

#5 Added method and hint method to delete Nth node from the end of a Linked List
  edualgo/LinkedList.py
Labels: Easy, Linked List, PyCon Devsprint, enhancement

#9 Insertion sort
  edualgo/algorithm.py
Labels: PyCon Devsprint, enhancement

#8 Readme tweaking
  README.md
Labels: documentation

#10 Added Bogo Sort under the class sort
  edualgo/algorithm.py
Labels: Easy, PyCon Devsprint, enhancement

#12 Added Binary Search Algorithm
  edualgo/binSearchAlgo.py
Labels: Easy, PyCon Devsprint, enhancement

#16 Refactored the algorithm.py to a separate subpackage
  edualgo/algorithm.py
  edualgo/algorithms/__init__.py
  edualgo/algorithms/matrices.py
  edualgo/algorithms/sort.py
  edualgo/algorithms/string_algorithms.py
Labels: PyCon Devsprint, enhancement

#18 Stack data structure code is added
  edualgo/stack.py
  setup.py
Labels: Intermediate, PyCon Devsprint, stack

#20 Sentence mistake in the function doc string of is_empty in stack.py is fixed
  edualgo/stack.py
Labels: PyCon Devsprint, bug, enhancement

#22 Added a new data structure Queue
  edualgo/queue.py
Labels: Intermediate, PyCon Devsprint, enhancement

#25 Added Merge sort algorithm.
  edualgo/algorithms/sort.py
Labels: PyCon Devsprint, documentation

#28 Update algorithm.py
  build/lib/edualgo/algorithm.py
Labels: Easy, enhancement, hacktoberfest2020

#31 Add Binary Tree Inorder Traversal
  edualgo/BinaryTree.py
Labels: Easy, Intermediate, enhancement, hacktoberfest2020

#34 Add Binary Tree PreOrder Traversal Method
  edualgo/BinaryTree.py
Labels: Intermediate, enhancement, hacktoberfest2020

#36 Added Binary Tree 'countNode' and 'KthLevel' methods
  edualgo/BinaryTree.py
Labels: BinaryTree, Intermediate, hacktoberfest2020

#38 Added quicksort algorithm with the hints
  edualgo/algorithms/sort.py
Labels: Easy, documentation, enhancement, hacktoberfest-accepted, hacktoberfest2020
