Repository edualgo/eduAlgo, pull requests merged in 2021-10, with the labels that each got.

#166 Added kruskal's algorithm
  edualgo/graph_algorithms/kruskal.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#171 Added KMP Pattern Matching algorithm (#159)
  edualgo/algorithms/KMP_Pattern_Matching.py
Labels: hacktoberfest-accepted, hacktoberfest2021, pattern-matching

#169 Identity comparison with singleton #163
  build/lib/edualgo/algorithm.py
  edualgo/BinaryTree.py
  edualgo/LinkedList.py
  edualgo/algorithms/matrices.py
  edualgo/algorithms/sort.py
  edualgo/algorithms/string_algorithms.py
  edualgo/backtracking_algorithms/Sudoku.py
  edualgo/backtracking_algorithms/m_coloring_problem.py
  edualgo/circular-linked-list.py
  edualgo/graph_algorithms/prim.py
  edualgo/greedy_algorithms/Minimum_Product_Subset.py
  edualgo/heap.py
  edualgo/maths/fibonacci.py
  edualgo/search_algorithms/exponential_search.py
  edualgo/search_algorithms/interpolation_search.py
  edualgo/search_algorithms/jump_search.py
  edualgo/search_algorithms/linear_search.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#170 Binary Search
  edualgo/search_algorithms/binary_search.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#172 Changed mutable default argument to immutable
  edualgo/heap.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#175 update linked list delete node method
  edualgo/LinkedList.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#176 Added Radix Sort
  edualgo/radix-sort.py
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2021

#190 Create subsequences_string.py
  edualgo/strings/subsequences_string.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#194 Use `items()` to iterate over a dictionary
  edualgo/algorithms/string_algorithms.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#195 Use `items()` to iterate over a dictionary
  build/lib/edualgo/algorithm.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#197 unnecessary `list` call - write as literal
  edualgo/algorithms/sort.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#196 Unused variable 'obj_fib_class'
  edualgo/maths/fibonacci.py
Labels: hacktoberfest-accepted, hacktoberfest2021

#192 Consider using identity comparison with singleton
  edualgo/search_algorithms/binary_search.py
Labels: hacktoberfest-accepted, hacktoberfest2021
