Repository edualgo/eduAlgo, pull requests merged in 2021-02, with the labels that each got.

#129 Update sort.py
  edualgo/algorithms/sort.py
Labels: Approved, Intermediate, SWOC, SWoC30, enhancement, good first issue

#130 Create Fibonacci.py
  edualgo/dynamic_programming/Fibonacci.py
  edualgo/maths/Fibonacci.py
Labels: SWOC, SWoC20

#132 Segment tree class added under algorithms folder
  edualgo/algorithms/segment_tree.py
Labels: Approved, Don't merge, Intermediate, Segment Tree, enhancement, good first issue
